default_stages: ["pre-commit", "pre-push"]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # - id: no-commit-to-branch
      #   args: ["--branch=main"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  # ruff with autofix should run before formatters
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        types_or: ["python", "pyi"]
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
        types_or: ["python", "pyi"]

  # nbqa hooks for applying ruff to Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff-check
        name: ruff check notebooks
        args: ["--fix", "--exit-non-zero-on-fix"]
        files: \.ipynb$
      - id: nbqa-ruff-format
        name: ruff format notebooks
        files: \.ipynb$

  - repo: https://github.com/pappasam/toml-sort/
    rev: v0.24.2
    hooks:
      - id: toml-sort
        name: Sort pyproject.toml
        entry: toml-sort
        files: pyproject.toml
        args: []

  - repo: local
    hooks:
      - id: poetry install
        name: Install dependencies
        language: system
        entry: poetry install --sync
        always_run: True
        verbose: True
        stages: ["post-checkout", "post-merge", "post-rewrite"]

      - id: pre-commit install
        name: Install pre-commit hooks
        language: system
        entry: poetry run pre-commit install-hooks
        always_run: True
        verbose: True
        stages: ["post-checkout", "post-merge", "post-rewrite"]

      # Run mypy locally to reuse cache
      - id: mypy
        name: Run mypy
        language: system
        types_or: ["python", "pyi"]
        entry: poetry run mypy
        require_serial: True

      # Run mypy on notebooks using nbqa locally to reuse cache
      - id: nbqa-mypy
        name: Run mypy on notebooks
        language: system
        files: \.ipynb$
        entry: poetry run nbqa mypy
        require_serial: True
